name: Lint, Test and Deploy Project
on: [workflow_dispatch]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v3
            - name: Install nodejs
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install packages
              run: npm ci
            - name: Linting
              run: npm run lint
            - name: Run test cases
              run: npm test
            - name: Build the project
              run: npm run build
            - name: Deploy
              run: echo "Deploying...."